# Generated by Django 5.1.4 on 2025-01-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
