# Generated by Django 5.1.4 on 2025-01-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
